### ISSUE TITLE
Had to change file suffix

### ISSUE THREAD

**Issue by codespleen** [nairdairda/Shopify-Font-Awesome#1]
As of 5/5/16, I needed to change 
font-awesome.min.css.**less**
to 
font-awesome.min.css.**liquid**

After that, it worked fine.

**Comment by nairdairda** [comment]
Thanks for letting me know! Fixed and updated to the latest Font-Awesome version. Cheers!

**Comment by kickmouth** [comment]
hi, excellent font awesome work.
any idea why it just won't work on firefox - beautiful on webkits - just not playing at all nicely on mozilla (and quite possibly IE, not checked yet)
all suggestion greatly appreciated.
cheers
j

**Comment by nairdairda** [comment]
@kickmouth Will look into this!
